# Generated by Django 4.2.7 on 2025-03-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('cantidad_minima', models.PositiveIntegerField(default=1)),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_activos', to='activos.fabricante')),
            ],
            options={
                'verbose_name': 'Stock Activo',
                'verbose_name_plural': 'Stock Activos',
                'ordering': ['nombre', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste de inventario')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.CharField(max_length=100)),
                ('destino', models.CharField(blank=True, max_length=200, null=True)),
                ('orden_trabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('stock_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='stock.stockactivo')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
    ]
