# Generated by Django 4.2.7 on 2025-03-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoObsoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100, unique=True)),
                ('ano_instalacion', models.PositiveIntegerField(verbose_name='Año Instalación')),
                ('vida_util', models.PositiveIntegerField(verbose_name='Vida Útil (años)')),
                ('estado_actual', models.CharField(choices=[('funcional', 'Funcional'), ('deteriorado', 'Deteriorado'), ('obsoleto', 'Tecnológicamente Obsoleto'), ('falla', 'Con Fallas Recurrentes'), ('discontinuado', 'Discontinuado por Fabricante')], max_length=20)),
                ('disponibilidad_repuestos', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('nula', 'Nula'), ('descontinuada', 'Descontinuada por Fabricante')], max_length=20)),
                ('estrategia_mitigacion', models.CharField(choices=[('reemplazo', 'Reemplazo Total'), ('actualización', 'Actualización'), ('extensión', 'Extensión de Vida Útil'), ('redesign', 'Rediseño del Sistema'), ('redundancia', 'Implementar Redundancia'), ('outsourcing', 'Outsourcing del Servicio'), ('otra', 'Otra Estrategia')], max_length=20)),
                ('fecha_renovacion', models.DateField(blank=True, null=True)),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('impacto_produccion', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('responsable_evaluacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_obsoletos', to='activos.fabricante')),
            ],
            options={
                'verbose_name': 'Activo Obsoleto',
                'verbose_name_plural': 'Activos Obsoletos',
                'ordering': ['nombre', 'modelo'],
            },
        ),
    ]
