# Generated by Django 4.2.7 on 2025-03-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='activos.area')),
            ],
            options={
                'verbose_name': 'Subárea',
                'verbose_name_plural': 'Subáreas',
                'ordering': ['area__nombre', 'nombre'],
                'unique_together': {('nombre', 'area')},
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='activos/')),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('precio_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='activos.area')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='activos.fabricante')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='activos.subarea')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['area__nombre', 'subarea__nombre', 'nombre'],
            },
        ),
    ]
