# Generated by Django 4.2.7 on 2025-03-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoCritico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100, unique=True)),
                ('impacto_produccion', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20)),
                ('disponibilidad_repuestos', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('nula', 'Nula')], max_length=20)),
                ('probabilidad_falla', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=20)),
                ('criticidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('extrema', 'Extrema')], max_length=20)),
                ('estrategia_recomendada', models.CharField(choices=[('reemplazo', 'Reemplazo Planificado'), ('stock', 'Mantener Stock'), ('monitoreo', 'Monitoreo Continuo'), ('mantenimiento', 'Mantenimiento Preventivo'), ('redundancia', 'Implementar Redundancia'), ('otro', 'Otra Estrategia')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('responsable_evaluacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_criticos', to='activos.fabricante')),
            ],
            options={
                'verbose_name': 'Activo Crítico',
                'verbose_name_plural': 'Activos Críticos',
                'ordering': ['-criticidad', 'nombre'],
            },
        ),
    ]
